resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/therealsohail/concourse-demo.git
      branch: master

jobs:
  - name: Package
    plan:
      - get: sources
        trigger: true
      - task: build-code
        file: sources/ci/build.yml
