resources:
  - name: node-repo
    type: git
    source:
      uri: https://github.com/therealsohail/concourse-demo.git
      branch: master

jobs:
  - name: Package
    plan:
      - get: node-repo
        trigger: true
      - task: build-code
        # file: node-repo/ci/build.yml
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: node, tag: slim }
        run:
          path: node-proj/ci/build.sh
