# resource_types:
  # - name: npm-cache
  #   type: docker-image
  #   source:
  #     repository: ymedlop/npm-cache-resource
  #     tag: latest


resources:
  - name: sources
    type: git
    source: 
      uri: https://github.com/therealsohail/concourse-demo.git
      branch: master

  # - name: dependency-cache
  #   type: npm-cache
  #   source:
  #     <<: *repo-source
  #     paths:
  #       - package.json

jobs:
  - name: package
    plan:
      - get: sources
        trigger: true
      - task: install
        file: sources/ci/build.yml

      - task: build-code
        # file: sources/ci/build.yml
        platform: linux

        image_resource:
          type: registry-image
          source: { repository: node }
        inputs:
          - name: sources
        run:
          path: sources/ci/build.sh
